# Generated by Django 5.1.6 on 2025-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cooperative', 'Cooperative'), ('buyer', 'Buyer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
