# Generated by Django 5.1.6 on 2025-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_producetype_alter_farmer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('nuts', 'Nuts'), ('herbs', 'Herbs'), ('grains', 'Grains')], default='vegetables', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants_count',
            field=models.IntegerField(default=0),
        ),
    ]
