# Generated by Django 4.2.7

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('cooperative', 'Category')
    
    # Create default categories
    categories = [
        {
            'name': 'Vegetables',
            'slug': 'vegetables',
            'description': 'Fresh vegetables from local farmers',
            'icon': 'fa-carrot',
            'color': '#84cc16',
            'display_order': 1
        },
        {
            'name': 'Fruits',
            'slug': 'fruits',
            'description': 'Fresh fruits from local farmers',
            'icon': 'fa-apple-alt',
            'color': '#f5922a',
            'display_order': 2
        },
        {
            'name': 'Herbs',
            'slug': 'herbs',
            'description': 'Fresh herbs and spices',
            'icon': 'fa-seedling',
            'color': '#15b181',
            'display_order': 3
        },
        {
            'name': 'Nuts',
            'slug': 'nuts',
            'description': 'Nuts and seeds',
            'icon': 'fa-nuts-mixed',
            'color': '#b45409',
            'display_order': 4
        },
        {
            'name': 'Grains',
            'slug': 'grains',
            'description': 'Grains and cereals',
            'icon': 'fa-wheat',
            'color': '#eab308',
            'display_order': 5
        }
    ]
    
    for category_data in categories:
        Category.objects.create(**category_data)

def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('cooperative', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_add_category_model'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]

