# Generated by Django 5.1.6 on 2025-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producetype',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
