# Generated by Django 5.1.6 on 2025-03-20 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0005_customer_bankaccount_order_orderitem_orderreview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='farmer',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
