# Generated by Django 5.1.6 on 2025-03-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0006_remove_farmer_address_remove_farmer_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Color code for the category', max_length=20, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='producetype',
            old_name='base_price',
            new_name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='producetype',
            name='image_url',
        ),
        migrations.AddField(
            model_name='producetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producetype',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='producetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='producetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce_types/'),
        ),
        migrations.AlterField(
            model_name='producetype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_types', to='cooperative.category'),
        ),
    ]
