# Generated by Django 5.1.6 on 2025-03-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_create_default_categories'),
        ('cooperative', '0007_category_and_more'),
    ]

    operations = [
    ]
