# Generated by Django 5.1.6 on 2025-03-20 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_merge_20250320_1702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperativeproduce',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='cooperativeproduce',
            old_name='province',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='cooperativeproduce',
            name='variant',
        ),
        migrations.AddField(
            model_name='cooperativeproduce',
            name='grade',
            field=models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D'), ('E', 'Grade E')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='cooperativeproduce',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cooperativeproduce',
            name='produce_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_items', to='cooperative.producetype'),
        ),
    ]
