# Generated by Django 5.1.6 on 2025-03-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0005_add_province_choices_to_farmer'),
        ('cooperative', '0005_alter_farmer_location'),
        ('cooperative', '0009_add_location_to_cooperative_produce'),
    ]

    operations = [
    ]
