# Generated by Django 5.1.6 on 2025-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0010_merge_20250320_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('nuts', 'Nuts'), ('herbs', 'Herbs'), ('grains', 'Grains'), ('roots_tubers', 'Roots & Tubers'), ('legumes', 'Legumes & Pulses'), ('coffee_tea', 'Coffee & Tea'), ('dairy', 'Dairy Products'), ('honey', 'Honey & Bee Products'), ('spices', 'Spices'), ('flowers', 'Flowers'), ('seeds', 'Seeds'), ('livestock', 'Livestock Products'), ('oils', 'Oils & Fats'), ('processed', 'Processed Foods'), ('organic', 'Organic Products'), ('specialty', 'Specialty Products'), ('medicinal', 'Medicinal Plants'), ('fish', 'Fish & Aquaculture'), ('other', 'Other Products')], default='vegetables', max_length=20),
        ),
    ]
